[tool.poetry]
name = "labs"
version = "0.1.0"
description = ""
authors = ["Shayan Taghinezhad Roudbaraki s301425 <s301425@studenti.polito.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
